services:
    security.authentication.wechat_provider:
        class: App\Security\Authentication\Provider\WechatProvider
        public: false
        abstract: true
        arguments: ["@app_wechat_user_provider"]

    security.authentication.wechat_listener:
        class: App\Security\Firewall\WechatListener
        arguments:
          $tokenStorage: '@security.token_storage'
          $authenticationManager: '@security.authentication.manager'
          $httpUtils: '@security.http_utils'
          $sdk: '@lilocon.wechat.sdk'
          $event_dispatcher: '@event_dispatcher'
          $options: {}

    wechat.factory.easywechat_factory:
        class: App\Factory\WeChatFactory

    lilocon.wechat.sdk:
        class: EasyWeChat\OfficialAccount\Application
        tags:
            name : monolog.logger
            channel: wechat
        factory: ['@wechat.factory.easywechat_factory','createNewInstance']
        arguments:
            $server: '@weixin.server'
            $logger: '@logger'


    app_wechat_user_provider:
        class: App\Providers\UserProvider
        arguments: ['@service_container']

    app.events.wechat_event_subscriber:
        class: App\Events\WechatEventSubscriber
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_subscriber }

